# Generated by Django 2.2.4 on 2019-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iamge',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
