# Generated by Django 2.2.4 on 2019-09-10 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190910_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='iamge',
            new_name='image',
        ),
    ]
